### ISSUE TITLE
How do I get the returning array from mandrill?

### ISSUE THREAD

**Issue by echan00** [dtaniwaki/mandriller#11]
I need the returning array from mandrill to track the ids of the emails I sent (to get click and read data), how would I do that?

    result = mandrill.messages.send message, async, ip_pool, send_at
        # [{"_id"=>"abc123abc123abc123abc123abc123",
        #     "reject_reason"=>"hard-bounce",
        #     "status"=>"sent",
        #     "email"=>"recipient.email@example.com"}]

**Comment by dtaniwaki** [comment]
Hi @echan00 
Thank you for using my gem.

I think you can try `return_response: true` and call `deliver` instead of `deliver!` to get the response.

So, it should be something like

```ruby
mail = YourMailer.your_action.deliver
```

**Comment by echan00** [comment]
@dtaniwaki thanks, its a great gem!

I ended up adding unique metadata to my emails instead and using that as a way to track :)
